[workspace]
members = ["ouroboros-core", "ouroboros-api", "ouroboros-napi"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
utoipa = { version = "4", features = ["axum_extras"] }
walkdir = "2"
