[workspace]
members = ["ouroboros-core", "ouroboros-api", "ouroboros-napi"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }