import { MakerZIP } from "@electron-forge/maker-zip";

export default {
  packagerConfig: {
    asar: false,
    prune: true,
    platforms: ["drawin", "linux", "windows"],
    arch: ["x64", "arm64"],
    dir:"dist2",
    ignore: [
      "^/.cargo",
      "^/.github",
      "^/electron",
      "^/napi",
      "^/script",
      "^/src",
      "^/targe",
      "^/target",
      "^/Cargo",
      "^/extension",
      ".gitignore",
      "tsconfig.json",
      "tsconfig.node.json",
      "vite.config.ts",
      "forge.config.mjs",
      "yarn.lock",
      "README.md",
      "doc",
      "ouroboros-core",
      "ouroboros-api",
      "ouroboros-napi",
      "ouroboros-electron",
      "ouroboros-web",
      "node_modules/.vite",
      "node_modules/@babel",
      "node_modules/@electron",
      "node_modules/@electron-forge",
      "node_modules/@esbuild",
      "node_modules/@he-tree",
      "node_modules/@dotenvx",
      "node_modules/@napi-rs",
      "node_modules/@npmcli",
      "node_modules/@rollup",
      "node_modules/@tsconfig",
      "node_modules/@types",
      "node_modules/@vue",
      "node_modules/@vueuse",
      "node_modules/@volar",
    ],
    // extraResource: ["resources/tray.png"],
  },
  makers: [new MakerZIP({}, ["darwin", "linux", "win32"])],
  publishers: [
    {
      name: "@electron-forge/publisher-github",
      config: {
        repository: {
          owner: "gsxhnd",
          name: "ouroboros",
        },
        prerelease: true,
      },
    },
  ],
};
