/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Tag {
  id: number
  name: string
  pid: number
  createdAt?: Date
  updatedAt?: Date
}
export declare class Database {
  static init(dbPath: string): Promise<Database>
  get(): Promise<Array<Tag> | null>
  getFolder(): Promise<Array<Tag> | null>
  sync(): Promise<void>
}
