[package]
name = "ouroboros-core"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["--cfg=sqlx_macros_unstable"]

[dependencies]
log = { version = "0.4" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "chrono"] }
walkdir = { workspace = true }
tokio = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
