name: Test window build napi

on:
  push:
    branches:
      - master

jobs:
  release:
    name: build and release electron app

    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: cd ouroboros-web/ && yarn install && yarn build && cd ..

      - name: intall rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - run: cargo check

      # build
      - run: pwd && ls -al
      - run: yarn run napi:release
      - run: yarn electron:build
      - run: ls ./dist
      - run: yarn package
      - run: yarn make
      - run: ls ./out

      - uses: actions/upload-artifact@v4
        with:
          name: ourobroros-windows-test
          path: |
            out/**/*.zip
